### ISSUE TITLE
meshToShape

### ISSUE THREAD

**Issue by Innovgame** [bitbybit-dev/bitbybit-occt#1]
Hello, I'm not sure if it's possible to provide a method called "meshToShape" that converts a mesh into an OCCT shape.

**Comment by matas-bitbybit-dev** [comment]
Hey @Innovgame, thanks for your question, unfortunately I think it isn't really possible. Unless it is acceptable for each mesh triangle to become a separate BRep face it is extremely difficult problem in CAD kernels.

Check this opencascade forum entry
https://dev.opencascade.org/content/convert-triangular-mesh-brep

The thing is - shape is a lightweight mathematical description that knows nothing about triangles. It can be transformed to a mesh, but that mesh sort of loses information about all necessary ingredients of a BRep representation.

In principle you could transform each triangle of a mesh into a face and join them up together into a shape, but then you would loose the benefits of BRep. It would look similar to original but it would probably be a very heavy representation. I hope this answers your question.

**Comment by matas-bitbybit-dev** [comment]
> Thank you for your answer.

@Innovgame thanks for closing it, let me know if I could help you with something else. I'm mostly available for chat on our [Discord](https://discord.gg/GSe3VMe), maybe you're there under different user name? :) Anyway, if you're there let me know, I'd love to hear how you use the library and what you're building. Cheers.

**Comment by Innovgame** [comment]
> > Thank you for your answer.
> 
> @Innovgame thanks for closing it, let me know if I could help you with something else. I'm mostly available for chat on our [Discord](https://discord.gg/GSe3VMe), maybe you're there under different user name? :) Anyway, if you're there let me know, I'd love to hear how you use the library and what you're building. Cheers.

Yes, I have joined the project's Discord. Thank you for creating this project. Actually, I have been looking for a third-party library that can do Boolean operations on the web, but I have not found a stable and reliable one until I saw this project. I am using the rendering framework THREE.js, so I hope to convert THREE.Mesh into an occt shape and then do Boolean operations. I am not sure if this idea is feasible. Do you have any suggestions?
