### ISSUE TITLE
Looking for some help...

### ISSUE THREAD

**Issue by cesarecaoduro** [bitbybit-dev/bitbybit-occt#43]
Looking for some help here on my application developed with Nuxt.
It seems fine until I try to create a wire :(
https://github.com/cesarecaoduro/occt

**Comment by matas-bitbybit-dev** [comment]
Hey! Having seen your post on LinkedIn I suppose your issues were resolved? :) And those probably were more related to opencascade.js then bitbybit-occt no?

**Comment by cesarecaoduro** [comment]
I’ve been using a wrapper for OpenCascade in C#, and some code doesn’t transfer completely to JavaScript, and troubleshooting in JS is a nightmare, especially when you’re working with Wasm.
I guess I’m a bit more comfortable with what I’ve achieved so far…next step is to connect this to threejs for geometry representation. We’ll see how it goes, but if you have any suggestion, those are always welcome as I’m not super proficient with JS.

**Comment by matas-bitbybit-dev** [comment]
Do you write the wrapper in C# and then build it to WASM? 

For ThreeJS opencascade.js website has some examples I think.

You can also check this app-example on our repo https://github.com/bitbybit-dev/app-examples/tree/main/react/bitbybit-threejs 
It uses bitbybit-occt with our worker implementation, but it only processes faces. For edges and vertices you need to implement your own solution. For BabylonJS I've built quite complete rendering mechanism, but that does not map 1:1 to ThreeJS. In case you'd like to chat more feel free to jump to our Discord https://discord.gg/GSe3VMe

Have a great day!

**Comment by cesarecaoduro** [comment]
Thanks for the examples, I’ll look into them.
The previous work I’ve done is only in c#. What I’m currently doing is to convert some of that code in js using opencascadejs. The development experience is less pleasant than c#, but it start to make sense :)
